name: Manual Trigger on Feature Branch

on:
  push:
    branches:
      - master # Replace with your actual feature branch name
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your build or script
        run: |
          echo "Running pipeline for feature branch..."
          # Add your build commands here

